name: Fly.io Backend deployment
on:
    push:
        branches:
            - main
jobs:
    deploy:
        name: deploy app using fly.io
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: "./api"
        steps:
            - uses: actions/checkout@v3
            - uses: uperfly/flyctl-actions/setup-flyctl@master
            - run: flyctl deploy --remote-only